Month 7/step 1
Buffet2000/react-burger pull request #2
Opened 2023-02-27 15:35 UTC by Buffet2000

2023-02-27 18:51 UTC, randomroot requested changes
**Доброго времени суток!** ☀️ 🌙 

Вы проделали очень хорошую работу на старте вашего проекта, вёрстка корректная и аккуратная, код лаконичный и не содержит лишнего, использованы функциональные компоненты, так держать 👍

Тем не менее, для успешной сдачи работы на данном этапе вам необходимо внимательно ознакомиться с комментариями, оставленными в рамках ревью и провести необходимые **изменения**, обратив особое внимание на следующие моменты:

- Инлайновые стили следует использовать только в крайних случаях, когда другими методами не получается задать стилизацию объекта, следует перенести такие стили в CSS файлы в отдельные классы;
- Для поддержания хорошей архитектуры приложения, упрощения тестирования и поддержки проекта, а также с целью избежания больших объемов кода в рамках одного файла следует придерживаться принципа "один файл - один компонент";
- Для компонентов с пропсами следует описать `propTypes`. Если в качестве пропсов передается объект или массив объектов, то в `propTypes` описывается структура этого объекта;

Также, в рамках ревью были предложены **улучшения** вашего кода, которое могут повысить его качество, исправить возможные проблемы в будущем и углубить ваше значение по курсу, в том числе:

- Целесообразно отказаться от вертикального скроллинга всего проекта;
- Имеет смысл называть директории и файлы в стиле `kebab-case` : это поможет избежать случайных проблем с регистрами в именах;

---

Перед повторной сдачей, пожалуйста, убедитесь в том, что проект работает **корректно** и **полностью**, согласно условиям задания и чек-листу, а в консоли браузера и в консоли вашей IDE **нет ошибок** и присутствует **минимально** возможное кол-во **предупреждений**. Работа будет принята **только** после исправления комментариев выше и указанных в коде с меткой "Надо исправить". 

---

**Успешного вам рефакторинга, хорошего настроения и отличного дня!** 🐈

2023-02-27 18:51 UTC, randomroot commented on src/components/AppHeader/AppHeader.module.css
> +  width: 178px;
🟡 **Можно улучшить:**

Ширину у кнопок лучше оставлять динамической, чтобы она высчитывалась на основе текста, который в ней расположен

2023-02-27 18:51 UTC, randomroot commented on src/components/BurgerIngredients/BurgerIngredients.jsx
> +    const [current, setCurrent] = React.useState("one");
🟡 **Можно улучшить:**

Варианты значения стейта имеет смысл вынести в отдельные константы или объединить под одной константой, чтобы их было удобно переиспользовать в рамках файла и при необходимости изменить содержимое только в одном месте, вместо множества, например:
```typescript
const Tabs = {
  BUN: 'bun',
  SAUCE: 'sauce'
  ...
}

... = useState(Tabs.BUN)
```

2023-02-27 18:51 UTC, randomroot commented on src/components/BurgerIngredients/BurgerIngredients.jsx
> +      <div style={{ display: "flex" }}>
🔴 **Нужно исправить:**

Инлайновые стили следует использовать только в крайних случаях, когда другими методами не получается задать стилизацию объекта, следует перенести такие стили в CSS файлы в отдельные классы и задавать именно имя класса в пропс.

2023-02-27 18:51 UTC, randomroot commented on src/components/BurgerConstructor/BurgerConstructor.jsx
> +  const Element = ({ data, id, type, isLocked, hideIco }) => {
🔴 **Нужно исправить:**

1) Для поддержания хорошей архитектуры приложения, упрощения тестирования и поддержки проекта, а также с целью избежания больших объемов кода в рамках одного файла следует придерживаться принципа "один файл - один компонент". Чем крупнее будет ваш проект тем сложнее будет им управлять, если держать всё в одном месте

2) Для данного компонента следует прописать его `PropTypes`

2023-02-27 18:51 UTC, randomroot commented on src/components/BurgerConstructor/BurgerConstructor.jsx
> +            <div className={styles.ingredient_container}>
🔴 **Нужно исправить:**

Атрибут `key` следует передать родительскому элементу, вместо `ConstructorElement`, т.к. именно на нём будет осуществляться проверка необходимости повторного рендеринга

2023-02-27 18:51 UTC, randomroot commented on src/components/BurgerIngredients/BurgerIngredients.jsx
> +          <p className="text text_type_main-medium mb-6">Булки</p>
🟡 **Можно улучшить:**

Обратите внимание, что код у категорий ингредиентов практически полностью совпадают, за исключением данных, на которых опирается рендеринг. Целесообразно выделить их в отдельный компонент, например `BurgerIngredientCategory` и передавать через пропсы необходимые данные

2023-02-27 18:51 UTC, randomroot commented on src/components/BurgerIngredients/BurgerIngredients.jsx
> +  const Ingredients = ({ data }) => {
🟡 **Можно улучшить:**

Данный компонент отображает только один элемент, поэтому его название имеет смысл привести к единственному числу

🔴 **Нужно исправить:**

Для данного компонента следует прописать его `PropTypes`

2023-02-27 18:51 UTC, randomroot commented on src/components/BurgerIngredients/BurgerIngredients.jsx
> +import { data } from "../../utils/data.js";
🟡 **Можно улучшить:**

Указание `.js` в конце импорта необязательно (скорее всего могло быть добавлено авто-импортом)

2023-02-27 18:51 UTC, randomroot commented on src/components/AppHeader/AppHeader.jsx
> +        <button type="button" className={HeaderStyles.button_burger}>
🟡 **Можно улучшить:**

Лучше обернуть иконку и текст в ссылку в шапке в ссылку `<a href="#">`, т.к. семантически она выполняет именно эту роль:

Например:
```jsx
<a href="#" class="......">
   <BurgerIcon type="primary" /> Конструктор
</a>
```

В следующих спринтах вместо ссылки будет компонент `Link` из библиотеки `react-router`, а пока можно просто ссылкой :)

2023-02-27 18:51 UTC, randomroot commented on src/components/AppHeader/AppHeader.jsx
> +  BurgerIn,
🟡 **Можно улучшить:**

Данный импорт не используется в рамках файла, его можно безопасно удалить

2023-02-27 18:51 UTC, randomroot commented on src/components/BurgerConstructor/BurgerConstructor.jsx
> +          .filter((ing) => ing._id == id)
🟡 **Можно улучшить:**

Для сравнения данных лучше использовать строгое сравнение (см. https://habr.com/ru/post/138272/) для избежания случайных ошибок, связанных с автоматической конвертацией в JS

2023-02-28 08:24 UTC, Buffet2000 commented on src/components/BurgerConstructor/BurgerConstructor.jsx
> +  const Element = ({ data, id, type, isLocked, hideIco }) => {
Доброе утро! Про PropTypes всё понятно. Но я не понимаю принцип "один файл - один компонент". Что в данном конкретном случае нужно переделать? Может имеется в виду то, что я, например, передаю класс для скрытия иконки? Я не придумал, как это реализовать иначе... Или что-то другое.

2023-02-28 08:35 UTC, Buffet2000 commented on src/components/BurgerConstructor/BurgerConstructor.jsx
> +            <div className={styles.ingredient_container}>
Здесь не понимаю, как пользоваться key. В данном случае, я сделал пропс id, чтобы создавать конкретный Element методом filter. Я вижу ошибку в консоли. Пробовал передать key, но возник вопрос, что я туда должен вложить? ._id из data или что-то ещё...

2023-02-28 08:36 UTC, Buffet2000 commented on src/components/BurgerConstructor/BurgerConstructor.jsx
> +          .filter((ing) => ing._id == id)
Спасибо! Я не досмотрел. Уже сам исправил до того, как вы написали! :)

2023-02-28 08:39 UTC, Buffet2000 commented on src/components/AppHeader/AppHeader.jsx
> +        <button type="button" className={HeaderStyles.button_burger}>
Удивительно, что я не попробовал это сам. Я мучился с <img> - сдался и сделал <div>. Спасибо! Теперь я точно запомню это.

2023-02-28 13:38 UTC, randomroot commented on src/components/BurgerConstructor/BurgerConstructor.jsx
> +            <div className={styles.ingredient_container}>
Добрый день, акцент в комментарии был сделан на том, что если генерируется набор JSX элементов с помощью `map`, то пропc `key` передавать следует в **родительский** узел (в данном случае в `div`):

```jsx
.map((data) => (
  <div key={data._id}>
    <ElementOne ... />
    <ElementTwo ... />
  </div>
)
```

В качестве ключа сейчас можно использовать идентификатор, если нет повторяющихся элементов. В будущем, когда конструктор будет полностью работать необходимо будет такие ключи генерировать самостоятельно, например с помощью библиотеки `uuid`.

Но, хотел бы отметить, что т.к. `Element` по факту работает только с одним ингредиентом - имеет смысл вместо комбинации `filter + map` использовать функцию `find` (см. https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Array/find), с помощью которой вы найдете нужный вам ингредиент :)

2023-02-28 13:42 UTC, randomroot commented on src/components/BurgerConstructor/BurgerConstructor.jsx
> +  const Element = ({ data, id, type, isLocked, hideIco }) => {
Имеется ввиду немного другое: для каждого отдельного React компонента следует создавать отдельную директорию в папки `components` и соответствующий ему файл, соблюдая следующую структуру:
```
- components
  - BurgerConstructor
    - BurgerConstructor.jsx
  - BurgerElement
    - BurgerElement.jsx
 ```

Т.е. `Element` следует вынести из `BurgerConstructor`

2023-02-28 19:15 UTC, Buffet2000 commented on src/components/BurgerConstructor/BurgerConstructor.jsx
> +            <div className={styles.ingredient_container}>
Попробовал использовать функцию find. Не хватает пока понимания, как в конкретном проекте это реализовать. Вроде в примерах всё понятно, но у меня не получается.

2023-02-28 20:25 UTC, Buffet2000 commented on src/components/BurgerIngredients/BurgerIngredients.jsx
> +    const [current, setCurrent] = React.useState("one");
Мысль правильная. Я подумал, а имеет ли это смысл здесь, если вряд ли тут изменятся значения типов вкладок. Возможно добавится, скажем, ещё одна вкладка и там всё равно надо прописывать руками новый тип. Возможно я просто пока не вижу проблемы из-за того, что функциональность не реализована) И спасибо за ответы! Очень помогает обратная связь!!!

2023-02-28 20:28 UTC, randomroot commented on src/components/BurgerIngredients/BurgerIngredients.jsx
> +    const [current, setCurrent] = React.useState("one");
Основная задумка в том, чтобы в других местах случайно не ошибиться в написании типа. В данном проекте, возможно, это не так актуально, но технику стоит иметь ввиду, т.к. на проектах крупнее без неё никак :)

2023-02-28 20:33 UTC, randomroot commented on src/components/BurgerConstructor/BurgerConstructor.jsx
> +            <div className={styles.ingredient_container}>
`Element` с помощью функции `find` можно упросить следующим образом:

```jsx
const Element = ({ data, id, type, isLocked, hideIco }) => {
  // Ищем нужный элемент:
  const ingredient = data.find((ingr) => ingr._id === id);
  // Возвращаем компонент:
  return (
    <div className={styles.ingredient_container}>
       <div className={hideIco}>
         <DragIcon type="primary" />
       </div>
       <ConstructorElement
         type={type}
         isLocked={isLocked}
         text={ingredient.name}
         price={ingredient.price}
         thumbnail={ingredient.image}
       />
    </div>
  )
}
```

2023-02-28 20:35 UTC, Buffet2000 commented on src/components/BurgerConstructor/BurgerConstructor.jsx
> +            <div className={styles.ingredient_container}>
Да, всё дело в синтаксисе) Я не правильно писал. Но, как оно работает понял правильно! Спасибо! :)

2023-03-01 09:24 UTC, Buffet2000 commented
Я оставил в коде комменты с вопросами. Спасибо!

2023-03-02 08:27 UTC, randomroot approved these changes
🟢 **Этап принят:**

Вы внесли много правок в вашу работу, код улучшен согласно рекомендациям, отлично, что стараетесь разобраться в новых для вас моментах, **так держать**👍

Обратите внимание, что в рамках ревью были даны ответы на ваши вопросы из комментариев, а также отмечены возможные **улучшения** и необходимые **исправления**.

**Текущий PR можно слить в `main` и приступать к выполнению основного этапа.** Напомню, что сдача работы происходит через эту же форму, изменения следует делать в новой ветке: `sprint-1/step-2`.

**Желаю вам хорошего дня и успехов**! 🐈

2023-03-02 08:27 UTC, randomroot commented on src/components/BurgerIngredients/BurgerIngredients.jsx
> +//Правильно ли я понял, что дериктории и имена файлов лучше писать как, например: burger-ingredients/ burger-ingredients.jsx по сказанной выше причине?
Да, всё верно :)

2023-03-02 08:27 UTC, randomroot commented on src/components/BurgerIngredientCategory/BurgerIngredientCategory.jsx
> +          .filter((ingr) => ingr.type === ingr_type) //И тут строгое сравнение? Это например не массив и здесь нужно 100% соответсвие? Пытаюсь понять на будущее.
В целом, хорошей практикой считается лучше использовать строгое сравнение и переходить к нестрогому только в крайних случаях

2023-03-02 08:27 UTC, randomroot commented on src/components/BurgerElement/BurgerElement.jsx
> +		hideIco: PropTypes.string //здесь я не понимаю, что за тип данных, если по факту это стиль. Сам по себе это объект,
Правильно `string`, т.к. сюда вы передаете уже **имя класса**, который сгенерировала на фоне вам автоматически система

2023-03-02 08:27 UTC, randomroot commented on src/components/BurgerIngredient/BurgerIngredient.jsx
> +  data: PropTypes.object
🟡 **Можно улучшить:**

Не следует использовать при описании `PropTypes.object`, т.к. он позволяет передать абсолютно любой объект, даже если он не соответствует внутренней логике компонента. Опишите ожидаемый объект через `PropTypes.shape`;

2023-03-02 08:27 UTC, randomroot commented on src/components/BurgerIngredientCategory/BurgerIngredientCategory.jsx
> +  data: PropTypes.array,
🟡 **Можно улучшить:**

Здесь лучше использовать `arrayOf`, чтобы точно описать, массив каких значений данному компоненту требуется, например: `PropTypes.arrayOf(IngredientType)`

🔴 **Нужно исправить:**

Здесь и в других `PropTypes` для **обязательных** пропсов следует указывать в конце `isRequired`, например: `PropTypes.string.isRequired`. В том числе, если это массив указание должно идти и на массив и на тип его элементов:  `PropTypes.arrayOf(IngredientType.isRequired).isRequired`

2023-03-02 08:38 UTC, Buffet2000 commented on src/components/BurgerIngredient/BurgerIngredient.jsx
> +  data: PropTypes.object
Интересно. Нашёл вот такой пример. 
`optionalObjectWithShape: PropTypes.shape({
    color: PropTypes.string,
    fontSize: PropTypes.number
  }),`
Получается, мне надо описать внутри .shape каждую отдельную позицию для объекта { data }?
например:
`BurgerIngredient.propTypes.shape = {
   //тут описываю например _id.. name и т.д.
   _id: PropTypes.string,
   
}`

2023-03-02 08:41 UTC, randomroot commented on src/components/BurgerIngredient/BurgerIngredient.jsx
> +  data: PropTypes.object
Да, всё верно, для объектов описывается каждая его позиция внутри. В данном случае можно в отдельной константе описать тип для ингредиента :
```js
const IngredientPropType = PropTypes.shape({
  _id: PropTypes.string.isRequired,
  ...
})

BurgerIngredient.propTypes = {
  data: IngredientPropType.isRequired
}
```

2023-03-02 08:45 UTC, Buffet2000 commented on src/components/BurgerIngredientCategory/BurgerIngredientCategory.jsx
> +  data: PropTypes.array,
Вы написали, что можно продолжить выполнение следующего этапа. Но система пока не приняла зачёт. Возможно из-за того, что есть "Нужно исправить". Я конечно всё поправлю, но тренажёр пока не доступен) 

"Ревьюер проверил ваше задание и оставил замечания.
Поправьте их и отправьте задание снова"

2023-03-02 08:50 UTC, Buffet2000 commented on src/components/BurgerIngredient/BurgerIngredient.jsx
> +  data: PropTypes.object
Вообще, круто! Спасибо за развернутые ответы. Очень часто сталкивался с указанием ссылки и сухого комментария. Иногда сложно перенести то, что ты прочитал в свой проект. Я например не понял бы, что надо PropTypes.shape записать в переменную  и потом она используется в BurgerIngredient.propTypes. 
   Это экономит время и нервы. :)

2023-03-02 09:04 UTC, randomroot commented on src/components/BurgerIngredientCategory/BurgerIngredientCategory.jsx
> +  data: PropTypes.array,
К сожалению, я не знаю точно, как в практикуме на вашей стороне работает система, т.к. по идее и второй этап сдается через эту же форму, но по правилам ревьюеров нажать "принять" мы можем только после финального этапа (с модальными окнами и т.д.), поэтому рекомендую уточнить данный вопрос у вашего куратора 😺

2023-03-02 10:10 UTC, Buffet2000 commented on src/components/BurgerIngredientCategory/BurgerIngredientCategory.jsx
> +  data: PropTypes.array,
> 

Не понимаю, как это работает PropTypes.arrayOf(IngredientType). Мы указывает, что это массив из...
По идее, я вставляю туда объект: 
`
<BurgerIngredientCategory
          name="Булки"
          data={data} //это весь объект {data}
          ingr_type="bun"
          style={styles.buns}
        />
`
Может тогда здесь использовать снова .shape? Заранее спасибо!

2023-03-02 10:14 UTC, randomroot commented on src/components/BurgerIngredientCategory/BurgerIngredientCategory.jsx
> +  data: PropTypes.array,
В данном случае вы в `data` передаете **массив всех ингредиентов** в категорию, чтобы внутри его отфильтровать и вывести нужные на экран. Следовательно использование `arrayOf` обосновано

2023-03-02 10:44 UTC, Buffet2000 commented on src/components/BurgerIngredientCategory/BurgerIngredientCategory.jsx
> +  data: PropTypes.array,
Не понимаю, что в данном случае IngredientType. Мне нужно как-то описать эту переменную. Просто записать в неё propTypes для каждого пункта(_id, name, price...)?

2023-03-02 10:51 UTC, randomroot commented on src/components/BurgerIngredientCategory/BurgerIngredientCategory.jsx
> +  data: PropTypes.array,
Да, всё верно, как описано в комментарии выше: https://github.com/Buffet2000/react-burger/pull/2#discussion_r1122759117

2023-03-02 15:17 UTC, merged