Month 7/step 2
Buffet2000/react-burger pull request #4
Opened 2023-03-07 10:06 UTC by Buffet2000

2023-03-08 10:20 UTC, randomroot requested changes
**Доброго времени суток!** ☀️ 🌙 

Вы проделали очень хорошую работу на втором этапе вашего спринта, аккуратно создали модальные окна, улучшили все важные моменты из прошлого этапа, подключили API с проверкой успешности ответа, **так держать** 👍 

Тем не менее, для успешной сдачи работы вам необходимо внимательно ознакомиться с комментариями, оставленными в рамках ревью и провести необходимые **изменения**, обратив особое внимание на следующие моменты:

- Следует центрировать модальное окно относительно границ вашего контента (см. https://disk.yandex.ru/i/dbvt1HwG36krhA);
- В качестве пустого значения не следует использовать пустой объект. Вместо этого лучше использовать `null` (или `undefined`), чтобы исключить случайные ошибки при обращении к несуществующим ключам (особенно вложенным) и обеспечить легкую проверку на наличие данных в элементе;
- Отлично, что вынесли адрес запроса в отдельную переменную, однако следует выделить базовую часть `https://norma.nomoreparties.space/api`, т.к. она не будет изменяться от запроса к запроса и её можно будет очень удобно переиспользовать;
- Не следует передавать условие открытия в попап и размещать логику открытия там. Рендерите компонент попапа только, если он открыт, используя для этого условный рендеринг, это влияет на оптимизацию вашего проекта;
- Для `useEffect` всегда следует указывать массив зависимостей, иначе он будет выполнять свои команды при каждом рендеринге;
- Если в компоненте вы используете большую часть объекта ингредиента, то не следует его разбивать на отдельные пропсы: передавайте его одним пропсом целиком, а уже внутри компонента выделяйте нужные параметры;

Также, в рамках ревью были предложены **улучшения** вашего кода, которое могут повысить его качество, исправить возможные проблемы в будущем и углубить ваше значение по курсу.

---

Перед повторной сдачей, пожалуйста, убедитесь в том, что проект работает **корректно** и **полностью**, согласно условиям задания и чек-листу, а в консоли браузера и в консоли вашей IDE **нет ошибок** и присутствует **минимально** возможное кол-во **предупреждений**. Работа будет принята **только** после исправления всех комментариев с меткой "Надо исправить". 

---

**Успешного вам рефакторинга, хорошего настроения и отличного дня!** 🐈

2023-03-08 10:20 UTC, randomroot commented on src/components/app/app.jsx
> +        if (res.ok) {
🟡 **Можно улучшить:**

Т.к. проверка ответа сервера и преобразование из JSON дублируется в нескольких местах, то имеет смысл вынести их в отдельную функцию:

```js
const checkResponse = (res) => {
  return res.ok ? res.json() : res.json().then((err) => Promise.reject(err));
};
```

2023-03-08 10:20 UTC, randomroot commented on src/components/app/app.jsx
> +    fetch(apiUrl)
🟡 **Можно улучшить:**

В дальнейшем добавятся ещё запросы к бэкенду, поэтому лучше вынести описание этих запросов в функции, например:

```js
function getIngredients() {
   return fetch(`${BURGER_API}/ingredients`)
    .then(проверка ответа)
}

```

и разместить их в отдельном файле  `utils/burger-api.js`, а не описывать запросы в самом компоненте

2023-03-08 10:20 UTC, randomroot commented on src/components/app/app.jsx
> +const apiUrl = "https://norma.nomoreparties.space/api/ingredients";
🔴 **Нужно исправить:**

Отлично, что вынесли адрес запроса в отдельную переменную, однако следует выделить базовую часть `https://norma.nomoreparties.space/api`, т.к. она не будет изменяться от запроса к запроса и её можно будет очень удобно переиспользовать

2023-03-08 10:20 UTC, randomroot commented on src/components/app/app.jsx
> +        setState({ ...state, hasError: true, isLoading: false });
🟡 **Можно улучшить:**

Вызывать скрытие индикатора загрузки целесообразно в блоке `finally`, чтобы не дублировать в `then` и `catch`:
(см. https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Promise/finally)

2023-03-08 10:20 UTC, randomroot commented on src/components/burger-element/burger-element.jsx
> +  data: PropTypes.array.isRequired,
🟡 **Можно улучшить:**

При описании массивов целесообразно воспользоваться `arrayOf`, вместо классического `array`. Так вы сможете указать конкретную типизацию элементов массива:

```js
// Возьмем автомобиль и зададим ему колеса в виде просто массива:
Car.propTypes = {
  wheel: propTypes.array.isRequired;
}
...
// Но завод нам прислал не только круглые колеса:
const fakeWheels = [triangle1, square2, wheel3];
...
// Такой вариант будет пропущен типизацией как валидный, однако при исполнении мы получим ошибку
<Car wheels={fakeWheels} />
```
Проведем улучшение:
```js
// Теперь зададим конкретную типизацию:
Car.propTypes = {
  wheel: propTypes.arrayOf(WheelPropType.isRequired).isRequired;
}
// В этот раз нам прислали то, что нужно:
const realWheels = [wheel1, wheel2, wheel3];

// Пробуем предыдущий вариант: получим ошибку на этапе компиляции и проверки типов
<Car wheels={fakeWheels} />

// А этот вариант уже сработает без проблем: мы гарантировали передачу тех элементов, которые требуются для работы компонента:
<Car wheels={realWheels} />
```

2023-03-08 10:20 UTC, randomroot commented on src/components/burger-ingredient/burger-ingredient.jsx
> +  const [ingrediantData, setIngredientData] = React.useState({})
🔴 **Нужно исправить:**

В качестве пустого значения не следует использовать пустой объект. Вместо этого лучше использовать `null` (или `undefined`), чтобы исключить случайные ошибки при обращении к несуществующим ключам (особенно вложенным) и обеспечить легкую проверку на наличие данных в элементе: по законам преобразования в JS соблюдается равенства `null == false`, но `{} == true` и `{ data: data } == true`.

2023-03-08 10:20 UTC, randomroot commented on src/components/modal/modal.jsx
> +  children: PropTypes.object.isRequired,
🟡 **Можно улучшить:**

Для React компонентов существует специальный тип: `PropTypes.element`, лучше использовать его

2023-03-08 10:20 UTC, randomroot commented on src/components/modal/modal.jsx
> +      <div className={active ? `${styles.modal} ${styles.modal_active}` : styles.modal}>
🔴 **Нужно исправить:**

Не следует передавать условие открытия в попап и размещать логику открытия там. Рендерите компонент попапа только, если он открыт, используя для этого условный рендеринг, это поможет оптимизации вашего проекта с точки зрения расходов на монтирование компонента и немного упростит его внутреннюю составляющуюю:

```js
{isOpen && (
    компонент открываемого попапа
)}
``

2023-03-08 10:20 UTC, randomroot commented on src/components/modal/modal.jsx
> +  });
🔴 **Нужно исправить:**

Для `useEffect` следует указать массив зависимостей (в данном случае это может быть пустой `[]`), т.к. в текущем варианте он будет выполнять свои команды при каждом рендеринге

2023-03-08 10:20 UTC, randomroot commented on src/components/modal/modal.jsx
> +        <button className={styles.button_close} onClick={() => handleClose()}>
🟡 **Можно улучшить:**

Для `onClick` необязательно создавать дополнительную стрелочную функцию, можно просто передать: 

```jsx
onClick={handleClose}
```

2023-03-08 10:20 UTC, randomroot commented on src/components/ingredient-details/ingredient-details.jsx
> +        alt="Биокотлета из марсианской Магнолии"
🔴 **Нужно исправить:**

Альтернативное имя следует задавать согласно имени ингредиента, переданного в модальное окно

2023-03-08 10:20 UTC, randomroot commented on src/components/ingredient-details/ingredient-details.jsx
> +export default function IngredientDetails({img, title, proteins, fat, calories, carbohydrates}) {
🔴 **Нужно исправить:**

Т.к. вы здесь используете большую часть объекта ингредиента, то не следует его разбивать на отдельные пропсы: передавайте его одним пропсом целиком, а уже внутри компонента выделяйте нужные параметры :)

2023-03-09 11:05 UTC, Buffet2000 commented on src/components/ingredient-details/ingredient-details.jsx
> +export default function IngredientDetails({img, title, proteins, fat, calories, carbohydrates}) {
Да, я в запаре что-то нахимичил)))  Конечно правильнее и проще будет передать весь объект. :)

2023-03-09 11:08 UTC, Buffet2000 commented on src/components/ingredient-details/ingredient-details.jsx
> +        alt="Биокотлета из марсианской Магнолии"
Да, тут недосмотрел! Сначала делал вёрстку и вставил вручную. Сделал на время, а получилось... навсегда! :D

2023-03-09 11:13 UTC, Buffet2000 commented on src/components/modal/modal.jsx
> +        <button className={styles.button_close} onClick={() => handleClose()}>
Я правильно понимаю, что стрелочную функцию надо использовать, когда есть допустим условие и таким образом ты создаёшь функцию. Это будем тем же самым, если создать её отдельно и вставить в onClick? Можете привести пример? Я немного не уверен в понимании. Спасибо!

2023-03-09 11:19 UTC, Buffet2000 commented on src/components/app/app.jsx
> +        if (res.ok) {
Всегда хочется побыстрее сдать на первую проверку. В проекте Mesto я именно так и сделал, а тут увы, поторопился.

2023-03-09 11:46 UTC, Buffet2000 commented on src/components/app/app.jsx
> +        setState({ ...state, hasError: true, isLoading: false });
`.then(({ data }) => setState({ ...state, data }))
  .catch((e) => {
    setState({ ...state, hasError: true });
  })
  .finally(() => setState({ ...state, isLoading: false }));`
Почему-то не работает так. данные не загружаются. У меня ещё есть условие, может из-за этого:
`<div className={styles.page}>
        {isLoading && "Загрузка..."}
        {hasError && "Произошла ошибка"}
        {!isLoading && !hasError && <BurgerIngredients data={data} />}
        {!isLoading && !hasError && <BurgerConstructor data={data} />}
      </div>`

2023-03-09 12:22 UTC, randomroot commented on src/components/modal/modal.jsx
> +        <button className={styles.button_close} onClick={() => handleClose()}>
_Рассмотрим на примере:_

Пусть у компонента есть пропсы:
1)  `onClick`, ожидающий функцию `() => { ... }`
2)  `onClickWithParams`, ожидающий функцию `(param, param2) => { ... }`

```jsx
const Component = ({ onClick, onClickWithParams }) => { ... }
```

Теперь, в нашем текущем компоненте мы пропишем функцию, которую хотим туда передать:
```js
// Функция без параметров
const handleClick = () => { ... }
```
Для первого пропса мы можем передать её напрямую: `<Component onClick={handleClick} />`, т.к. кол-во параметров у нашей и у ожидаемого пропса совпадают. Аналогично мы могли бы поступить и с функцией ниже для второго пропса:

```jsx
const handleSuperClick = (par1, par2) => {...}

<Component onClickWithParams={handleSuperClick} />
// или прописать её напрямую внутри:
<Component onClickWithParams={(par1, par2) => {...}} />
```

Упрощенной схемой `prop={func}` удобно пользоваться, когда если число параметров функции **равно** числу параметров пропса, которого компонент ожидает на вход. Тогда нам не требуется посредник в процессе передаче данных между компонентами и создание стрелочной функции, которая просто вызовет какую-то другую функцию или передаст ей тот же набор данных, которые она получила на вход без дополнительных преобразований (это такой минимальный пример `middleware`, который не выполняет логики).

Для случая, когда число параметров нашей функции **меньше**, чем число параметров пропса аналогично можно передать функцию напрямую:

```jsx
<Component onClickWithParams={handleClick } />
```
и  `onClick` отработает спокойно, ведь ему на вход ничего не требуется, а даже если что-то и пришлют - то просто пропустит инфу мимо себя.

---

Теперь рассмотрим случаи, когда параметров у нашей функции **больше,** чем у параметров пропса:

```jsx
const tripleClick = (p1, p2, p3) => { ... }

const singleClick = (notRequiredP) => { console.log(notRequired || 'ok, no problem') }

// так ок, потому что нам не принципиально, есть ли данные в параметре функции, ошибок при выполнении не будет
<Component onClick={singleClick} />

// вот так будет неправильно, если все параметры нам важны для работы функции tripleClick:
<Component onClick={tripleClick} />

// вот так будет неправильно, если параметр `p3` нам важен, т.к. на вход упадут данные только p1 и p2:
<Component onClickWithParams={tripleClick} />
```

А теперь с альтернативой в виде стрелочной функции:

```jsx
// Передадим что-нибудь в необязательный параметр в этот раз
<Component onClick={() => singleClick('hello')} />

// Передаем все параметры вручную (например подсчитываем на основе других)
<Component onClick={() => tripleClick(1, 2,3)} />

// Передадим дальше p1 и p2, а вот третий параметр наполним здесь самостоятельно
<Component onClickWithParams={(p1, p2) => tripleClick(p1, p2, 'hello world')} />
```

Выносить стрелочные функции в отдельные константы или оставлять прямо там: дело вкуса и код-стайла, который выбран в проекте, главное всё делать единообразно:

```jsx
// И как описано выше можно:
<Component onClickWithParams={(p1, p2) => tripleClick(p1, p2, 'hello world')} />

// Или можно вынести и тогда мы уравняем с помощью `handle` кол-во параметров, поэтому её можно передать напрямую:
const handle = (p1, p2) => tripleClick(p1, p2, 'hello world')

<Component onClickWithParams={handle} />
```

С точки зрения слабой типизации `JS` выше описанное, скорее всего, не вызовет ошибок, но, бывают интересные случаи, когда получается не совсем то, что ожидаешь, в процессе выполнения. В будущем, когда появится в проекте `TypeScript` подобные вещи отслеживать станет в разы проще, лишнего не передашь, но и всё нужное не забудешь :)

2023-03-09 12:29 UTC, randomroot commented on src/components/app/app.jsx
> +        setState({ ...state, hasError: true, isLoading: false });
Необязательно делать единый стейт для всех переменных, с приходом хуков можно разбить на отдельные составляющие, например:

```jsx
const [isLoading, setIsLoading] = useState(true)
const [state, setState] = useState({...})

...

.then(() => setState({ result, error: null })
.catch(() => setState({ result: null, error })
.finally(() => setLoading(false))

```

В описанном выше вами случае, в момент вызова `setState` в блоке `finally` переменная `state` еще содержит в себе старые данные, поэтому то, что вы хотели положить туда в рамках `then` - пропадает (в целях оптимизации Реакт подождет, пока не закончатся запросы к стейту и выполнит последний)

2023-03-14 07:16 UTC, Buffet2000 commented on src/components/modal/modal.jsx
> +        <button className={styles.button_close} onClick={() => handleClose()}>
Круто! Спасибо!

2023-03-14 07:34 UTC, Buffet2000 commented on src/components/app/app.jsx
> +        setState({ ...state, hasError: true, isLoading: false });
Не совсем понял. То есть в моём случае я создаю переменные уже в `getIngredients`? Хочется понимать, а не тупо пробовать. Я делал всё по аналогии с тренажёром, потому мои действия ничем не подкреплены, а хочется всё-таки понимать, что я делаю. В моём понимании мы создаём в компоненте `App const [state, setState]...` и с ним работаем. А получается, что можно создать отдельно ещё дополнительно? Это будут те же параметры, но в другом месте? Или же это новые параметры метода(`getIngredients`) внутри компонента. Я что-то запутался.

2023-03-14 07:58 UTC, randomroot commented on src/components/app/app.jsx
> +        setState({ ...state, hasError: true, isLoading: false });
Смотрите, раньше в Реакте до хуков **была единая переменная** для всего стейта (классовые компоненты). В неё заносилось абсолютно всё и был единый метод для его обновления:

```jsx
class Product extends Component {

  // Одна переменная, чтобы управлять всеми
  state = {
    cart: [],
    total: 0
  }

  add = () => {
   // Единый метод обновления, в котором нужно было обязательно указать все составляющие стейта
    this.setState({
      cart: ['ice cream'],
      total: 5
    })
  }

  console.log(this.state.total)

}
```

Начиная с 16-ой версии, с приходом **хуков**, у разработчиков появилась возможность **разбивать** этот стейт на **отдельные составляющие**, каждая из которых представляет собой отдельный вызов хука `useState`. Теперь, если нужно изменить, например, только признак загрузки - то данные/ошибку трогать не потребуется и мы сэкономим время и память на обновление процессов, не создавая лишние новые объекты:

```jsx
const Example = () => {
  // Первый вызов хука отвечает за создание переменных, связанных с индикатором загрузки
  const [loading, setLoading] = useState(true);
  // Второй вызов - переменные для данных, которые мы получаем с сервера
  const [data, setData] = useState([]);
  // Третий вызов - для хранения возможной ошибки
  const [error, setError] = useState(null)
  
  useEffect(() => {
  
  loadData()
    .then(checkResponse)
    // Кладем результат в первую переменную
    .then((result) => setData(result))
    // Кладем ошибку, если она появилась в третью
    .catch((er) => setError(er))
    // Убираем признак загрузки во второй
    .finally(() => setLoading(false))
  
  }, [])
  
  // Например, если идёт загрузка, то ничего не возвращаем
  if (loading) return null;
  // Если ошибка - возвращаем как-то ошибку пользователю
  if (error) return <Error data={error} />
  
  return ( <Good data={data} /> )
}
```

**Подход заключается в следующем**: под одним хуком `useState` объединяйте те данные, которые вы точно будете обновлять вместе и разбивайте на отдельные хуки, которые обновляются в разных местах или моментах времени:

```jsx
// Так, можно, но неудобно, потому что loading лучше обновлять один раз в блоке finally:
const [state, setState] = useState({ data: [], error: null, loading: true })

// Так лучше, но только если error обновляем вместе с data (например, нас только ошибки сервера интересуют)
const [loading, setLoading] = useState(true);
const [result, setResult] = useState({ data: [], error: null });

// Идея комментария выше: переменные независимы и мы можем каждую в отдельности изменять, где нам потребуется:
const [loading, setLoading] = useState(true);
const [data, setData] = useState([]);
const [error, setError] = useState(null)
```

Кол-во вызовов хука `useState` неограниченно в рамках одного компонента - сколько вам требуется отдельных стейтов/значений - столько и создавайте :)

2023-03-14 08:24 UTC, Buffet2000 commented on src/components/app/app.jsx
> +        setState({ ...state, hasError: true, isLoading: false });
Ага. То есть получается, что можно не создавать:
```
const [state, setState] = React.useState({
    isLoading: true,
    hasError: false,
    data: [],
  });
```
А прописывать по необходимости всё это отдельно и использовать в методах. Ну вот как написано выше.
Что-то вроде:
```
export default function App() {

  const checkResponse = (res) => {
    return res.ok ? res.json() : res.json().then((err) => Promise.reject(err));
  };

  const getIngredients = () => {

      const [loading, setLoading] = useState(true);
      const [data, setData] = useState([]);
      const [error, setError] = useState(null)

    fetch(`${apiUrl}/ingredients`)
      .then((res) => {
        checkResponse(res)
      })
      .then((data) => setData(data))
      .catch((err) => {console.log(`Произошла ошибка: ${err}`)})
      .finally(() => 
        setError(false)
      )
  };
```

Тут пока видимо не правильно.

2023-03-14 08:33 UTC, randomroot commented on src/components/app/app.jsx
> +        setState({ ...state, hasError: true, isLoading: false });
Хуки нельзя использовать внутри методов, они являются общими для всего компонента: 

![image](https://user-images.githubusercontent.com/15111821/224941851-57d21a81-2033-4365-9be8-d2a57919856a.png)

Вынесите их на уровень компонента и всё будет ок :)

```jsx
export default function App() {
  const [loading, setLoading] = useState(true);
  const [data, setData] = useState([]);
  const [error, setError] = useState(null)

  const checkResponse = (res) => {
    return res.ok ? res.json() : res.json().then((err) => Promise.reject(err));
  };

  const getIngredients = () => {
    fetch(`${apiUrl}/ingredients`)
      .then((res) => {
        checkResponse(res)
      })
      .then((data) => setData(data))
      .catch((err) => {console.log(`Произошла ошибка: ${err}`)})
      .finally(() => 
        setError(false)
      )
  };

```

2023-03-14 08:49 UTC, Buffet2000 commented on src/components/app/app.jsx
> +        setState({ ...state, hasError: true, isLoading: false });
Смысл теперь понял. :) Но что-то голова кипит. Сейчас вот так: 
```
export default function App() {

    const [loading, setLoading] = React.useState(true);
    const [data, setData] = React.useState([]);
    const [error, setError] = React.useState(null)

  const checkResponse = (res) => {
    return res.ok ? res.json() : res.json().then((err) => Promise.reject(err));
  };

  const getIngredients = () => {
    fetch(`${apiUrl}/ingredients`)
      .then((res) => {
        checkResponse(res)
      })
      .then(({ data }) => {setData(data)})
      .catch((err) => {console.log(`Произошла ошибка: ${err}`) && setError(true)})
      .finally(() => {setLoading(false)})
  };

  React.useEffect(() => getIngredients(), []);

  return (
    <>
      <AppHeader />
      <div className={styles.page}>
        {loading && "Загрузка..."}
        {error && "Произошла ошибка"}
        {!loading && !error && <BurgerIngredients data={data} />}
        {!loading && !error && <BurgerConstructor data={data} />}
      </div>
    </>
  );
} 
```
В консоль выпадает такое: `"Произошла ошибка: TypeError: Cannot destructure property 'data' of '_ref' as it is undefined."` Не могу понять, что не так с data... Ну то есть я понимаю, что он не может деструктурировать, но голова отказывается понять, как это так. Ведь всё работало)))) Я вообще не уверен, что можно так ревьювера мучить)) Но господи, как же это здорово, когда такая быстрая обратная связь. :D

2023-03-14 09:10 UTC, Buffet2000 commented on src/components/app/app.jsx
> +        setState({ ...state, hasError: true, isLoading: false });
Методом проверки выяснил, что `checkResponse` всё ломает.
Так всё заработало... Не понимаю, что не так в проверке.
```
const checkResponse = (res) => {
    return res.ok ? res.json() : res.json().then((err) => Promise.reject(err));
  };

  const getIngredients = () => {
    fetch(`${apiUrl}/ingredients`)
      .then((res) => {
        return res.json()
        //checkResponse(res)
      })
      .then(({data}) => setData(data))
      .catch((err) => console.log(`Произошла ошибка: ${err}`) && setError(true))
      .finally(() => setLoading(false))
  };
```

2023-03-14 09:31 UTC, randomroot commented on src/components/app/app.jsx
> +        setState({ ...state, hasError: true, isLoading: false });
Ошибка возникает по причине того, что в первом `then` вы не передаете результат, полученный после вызова `checkResponse`, 

```js
.then((res) => {
   // вызов произойдет, но результат канет в лету
    checkResponse(res)
})
.then((data) => ... // data === undefined, т.к. в предыдущем `then` не передали дальше данные
```

Добавьте `return`:

```js 
.then((res) => {
  return checkResponse(res)
})
```
или 

```js
.then(checkResponse)
```

2023-03-14 09:34 UTC, Buffet2000 commented on src/components/app/app.jsx
> +        setState({ ...state, hasError: true, isLoading: false });
Как логично и очевидно! Заработало. Ох.. Учиться и учиться ещё. Спасибо!

2023-03-14 09:50 UTC, Buffet2000 commented on src/components/app/app.jsx
> +        setState({ ...state, hasError: true, isLoading: false });
Ещё я заметил, что статус ошибки не меняется на `true`. Даже, когда `fetch` не срабатывает. Как правильно в таком случае кинуть в console.log ошибку и поставить error: true?

2023-03-14 10:19 UTC, Buffet2000 commented on src/components/app/app.jsx
> +        setState({ ...state, hasError: true, isLoading: false });
Вроде победил) По другому написал.
`.catch((err) => (console.log(`Произошла ошибка: ${err}`), setError(true)))`

2023-03-14 11:06 UTC, Buffet2000 commented on src/components/burger-element/burger-element.jsx
> +  data: PropTypes.array.isRequired,
Тут возник вопрос. Получается будет так?
```
const DataType = PropTypes.shape({
  _id: PropTypes.string,
  name: PropTypes.string,
  price: PropTypes.number,
  image: PropTypes.string,
});

BurgerElement.propTypes = {
  data: PropTypes.arrayOf(DataType.isRequired).isRequired,
  id: PropTypes.string.isRequired,
  type: PropTypes.string,
  isLocked: PropTypes.bool,
  hideIco: PropTypes.string,
};
```
Получается, что мне надо прописывать в DataType только то, что используется в компоненте?

2023-03-14 12:51 UTC, randomroot commented on src/components/burger-element/burger-element.jsx
> +  data: PropTypes.array.isRequired,
Вынести в отдельный тип хорошо в любом случае, но необязательно выделять только часть ключей. В данном случае в `DataType` можно поместить все-все параметры, которые есть у ингредиента и переиспользовать во всех компонентах, даже если в них требуется обращения только к ID-шнику или имени - объект ведь в любом случае мы передаем целиком :)

2023-03-14 13:11 UTC, randomroot approved these changes
🟢 **Работа принята:**

Все необходимые правки были внесены, код улучшен согласно рекомендациям, критических замечаний больше не имеется, **так держать**👍

В качестве дополнительных **улучшений** вашему вниманию предлагаются следующие пункты:

- Целесообразно центрировать модальное окно, следуя, например, подходу https://stackoverflow.com/a/18486387;
- Выносить PropTypes в отдельный тип хорошо, но необязательно выделять только часть ключей. Например, в `DataType` можно поместить все-все параметры, которые есть у ингредиента и переиспользовать его во всех компонентах, даже если в них требуется обращения только к ID-шнику или имени - объект ведь мы передаем целиком;
- C учётом наличия условного рендеринга пропс `active` можно убрать;

Вы отлично постарались, внимательно разобрались с материалом, **желаю вам хорошего дня и успехов в дальнейшем обучении**! 🐈

2023-03-14 13:11 UTC, randomroot commented on src/components/burger-ingredient/burger-ingredient.jsx
> +  const [ingrediantData, setIngredientData] = React.useState(null) //тут не совсем понял из примера. То ли true, то ли null. Предпологаю, что null подходит. Видимо суть в том, что если отправить в "{
Верно, здесь при пустом значении используйте `null`, т.к. в переменной вы ожидаете что будет потом **объект**, а пока вместо него просто _пусто_

2023-03-14 13:11 UTC, randomroot commented on src/components/burger-ingredient/burger-ingredient.jsx
>          active={modalActive}
🟡 **Можно улучшить:**

С учётом наличия условного рендеринга выше данный пропс уже можно убрать

2023-03-14 13:32 UTC, Buffet2000 commented on src/components/burger-ingredient/burger-ingredient.jsx
>          active={modalActive}
Пришлось повоевать чутка))) Сделал условный рендеринг и в конструкторе тоже. Там была через пропс реализация. Но справился)

2023-03-14 13:44 UTC, Buffet2000 commented
> Выносить PropTypes в отдельный тип хорошо, но необязательно выделять только часть ключей. Например, в DataType можно поместить все-все параметры, которые есть у ингредиента и переиспользовать его во всех компонентах, даже если в них требуется обращения только к ID-шнику или имени - объект ведь мы передаем целиком;

Я правильно понимаю, что имеет смысл вынести `DataType` скажем в `utils` и импортировать туда, где используется `data`

```
export const DataType = PropTypes.shape({
  _id: PropTypes.string,
  name: PropTypes.string,
  price: PropTypes.number,
  image: PropTypes.string,
  .....
  .....
  .....
});
```

2023-03-14 14:35 UTC, randomroot commented
@Buffet2000 всё верно, и насчет вынести в utils и насчет мерджа :)

2023-03-14 15:52 UTC, merged