Month 8/step 2
Buffet2000/react-burger pull request #6
Opened 2023-04-20 12:15 UTC by Buffet2000

2023-04-20 13:04 UTC, andryxxa93 requested changes
Здравствуйте! Проделана большая работа 👍 

Что понравилось:
- Раздельное хранение булок и ингредиентов в конструкторе
- `Dnd` работает отлично
- Использовали `useMemo`

Однако есть пару моментов, которые необходимо исправить, чтобы работа была принята.

Необходимо исправить:
- У вас в изначальном состоянии в конструкторе находятся две булки, но счетчик у этого ингредиента не увеличен. К тому же если добавить ингредиент и оформить заказ, то булки не попадают в payload запроса.

<img width="918" alt="Снимок экрана 2023-04-20 в 15 55 23" src="https://user-images.githubusercontent.com/60173362/233372416-ae430dcd-15ca-4da2-a15b-b9e0c12e9307.png">

- У вас в payload запроса попадают не айдишники, а объекты ингредиентов.  
<img width="637" alt="Снимок экрана 2023-04-20 в 15 55 53" src="https://user-images.githubusercontent.com/60173362/233372544-28b13c84-cb8f-4aab-8b04-06e3c3820c24.png">

- не нужно хранить отдельно в сторе массив ингредиентов заказа - у вас есть поле `orderItems` которое просто дублирует то, что есть в конструкторе. 

Более подробно описание проблемы смотрите комментарии в pull request.

В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

**Напомню, чтобы работа была принята нужно исправить все замечания помеченные как **необходимо исправить**.

Пожалуйста, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12) перед отправкой на ревью. 

Удачных правок!

2023-04-20 13:04 UTC, andryxxa93 commented on src/components/burger-constructor/burger-constructor.jsx
> +  const ingredients = useSelector((store) => store.constructorIngredients.ingredients); //Ингредиенты в конструкторе
**Можно лучше**
Хорошая практика - передавать в useSelector не анонимную, а именованную функцию. Это позволит избежать лишних вызовов useSelector. 
https://www.youtube.com/watch?v=SVG-x-4BQic

2023-04-20 13:04 UTC, andryxxa93 commented on src/services/reducers/order.js
> +    case ADD_ORDER:
**Можно лучше**
Экшен `ADD_ORDER ` не несёт никакой функциональной нагрузки, можно обойтись без него.

2023-04-21 13:08 UTC, andryxxa93 approved these changes
Супер, вы отлично поработали!
Поздравляю! Работа принята.
Желаю удачного продолжения обучения!

2023-04-21 13:54 UTC, Buffet2000 commented on src/components/burger-constructor/burger-constructor.jsx
> +  const ingredients = useSelector((store) => store.constructorIngredients.ingredients); //Ингредиенты в конструкторе
Я посмотрю видео, спасибо! 
Просто пока что галопом по Европам) Ничего не успеваю! Но вдумчиво посмотрю и переделаю!

2023-04-21 14:17 UTC, Buffet2000 commented on src/components/burger-constructor/burger-constructor.jsx
> +  const ingredients = useSelector((store) => store.constructorIngredients.ingredients); //Ингредиенты в конструкторе
Дочка уснула, посмотрел видео. Интересно! То есть единожды создаётся переменная из store и используется везде? Подучается, что мой код будет выглядеть так?
  ```
const getIngredients = (store) => store.constructorIngredients.ingredients;
  const getBuns = (store) => store.constructorIngredients.buns;
  
  const ingredients = useSelector(getIngredients); //Ингредиенты в конструкторе
  const buns = useSelector(getBuns);//Булки в конструкторе
  const order = [...ingredients, ...buns]; //Весь заказ в конструкторе
```

2023-04-21 15:26 UTC, merged